version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: starbucks-postgres
    environment:
      POSTGRES_DB: starbucks_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin 
    ports:
      - "5432:5432"
    networks:
      - starbucks-network
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  starbucks-network:
    driver: bridge

volumes:
  db_data:
